const { xpathFunctionWithString, xpathFunctionWithIndex, xpathFunctionWithTwoStrings } = require("./ardisFunctions");

module.exports = {
    username: '//input[@placeholder="Username"]',
    password: '//input[@placeholder="Password"]',
    loginButton: "//*[contains(text(),'Login')]",
    inputSearchField: '//input[@placeholder="First name, last name, middle name"]',
    searchButton: "//*[@class='search-btn']//*[contains(text(),'Search')]",
    resultCount: '.col-xs-12>.count',
    searchResultName: "//*[@class='col-xs-10']//*[contains(text(),'Ziad Khalaf Al-manaser')]",
    aka: xpathFunctionWithString("Aka"),
    akaNamesList: xpathFunctionWithIndex(4),
    alerts: xpathFunctionWithString("Alerts"),
    alertsList: xpathFunctionWithIndex(7),
    text:"the family was featured in Forbes Arabia's Wealth List of 2009was featured in Forbes Middle East`s World's 100 Richest Arabs's List of 2015mentioned in Pandora Papers leaksRelated to a listed entityRelated to a state owned entityClose Associates of PEPsRelated to another sanctioned entity through a third party",
    avatar: ".grayscale",
    date: xpathFunctionWithString("Date"),
    dateOfBirth: xpathFunctionWithIndex(2),
    tin: xpathFunctionWithString("Tin"),
    tinText: xpathFunctionWithIndex(5),
    nationalId: xpathFunctionWithString("National"),
    nationalIdText: xpathFunctionWithIndex(6),
    biography: xpathFunctionWithString("Bio"),
    biographyText:xpathFunctionWithIndex(3),
    relatedOrg: xpathFunctionWithTwoStrings("Organizations"),
    relatedOrgText: xpathFunctionWithIndex(11),
    relatedPeople: xpathFunctionWithTwoStrings("People"),
    relatedpeopleText: xpathFunctionWithIndex(10),
    address: xpathFunctionWithString("Address"),
    addressText: xpathFunctionWithIndex(9),
    jurisdiction: xpathFunctionWithString("Aff"),
    jurisdictionText: xpathFunctionWithIndex(8),

}
