module.exports = {
    username: '//input[@placeholder="Username"]',
    password: '//input[@placeholder="Password"]',
    loginButton: "//*[contains(text(),'Login')]",
    inputSearchField: '//input[@placeholder="First name, last name, middle name"]',
    searchButton: "//*[@class='search-btn']//*[contains(text(),'Search')]",
    resultCount: '.col-xs-12>.count',
    searchResultName: "//*[@class='col-xs-10']//*[contains(text(),'Ziad Khalaf Al-manaser')]",
    aka: "//*[contains(text(),'Aka')]",
    akaNamesList: "(//*[@class='wordBreak'])[4]",
    alerts: "//*[contains(text(),'Alerts')]",
    alertsList: "(//*[@class='wordBreak'])[7]",
    text:"the family was featured in Forbes Arabia's Wealth List of 2009was featured in Forbes Middle East`s World's 100 Richest Arabs's List of 2015mentioned in Pandora Papers leaksRelated to a listed entityRelated to a state owned entityClose Associates of PEPsRelated to another sanctioned entity through a third party",
    avatar: ".grayscale",
    date: "//*[contains(text(),'Date')]",
    dateOfBirth: "(//*[@class='wordBreak'])[2]",
    tin: "//*[contains(text(),'Tin')]",
    tinText: "(//*[@class='wordBreak'])[5]",
    nationalId: "//*[contains(text(),'National')]",
    nationalIdText: "(//*[@class='wordBreak'])[6]",
    biography: "//*[contains(text(),'Bio')]",
    biographyText:"(//*[@class='wordBreak'])[3]",
    relatedOrg: "//*[contains(text(),'Related Organizations')]",
    relatedOrgText: "(//*[@class='wordBreak'])[11]",
    relatedPeople: "//*[contains(text(),'Related People')]",
    relatedpeopleText: "(//*[@class='wordBreak'])[10]",
    address: "//*[contains(text(),'Address')]",
    addressText: "(//*[@class='wordBreak'])[9]",
    jurisdiction: "//*[contains(text(),'Aff')]",
    jurisdictionText: "(//*[@class='wordBreak'])[8]"
}