const { xpathFunctionWithString, xpathFunctionWithIndex, xpathFunctionWithTwoStrings, xpathFunctionNameFiller, xpathContainsText } = require("./ardisFunctions");

module.exports = {
    username: '//input[@placeholder="Username"]',
    password: '//input[@placeholder="Password"]',
    loginButton: "//*[contains(text(),'Login')]",
    inputSearchField: '//input[@placeholder="First name, last name, middle name"]',
    searchButton: "//*[@class='search-btn']//*[contains(text(),'Search')]",
    resultCount: '.col-xs-12>.count',
    aka: xpathFunctionWithString("Aka"),
    akaNamesList: xpathFunctionWithIndex(4),
    alerts: xpathFunctionWithString("Alerts"),
    alertsList: xpathFunctionWithIndex(7),
    avatar: ".grayscale",
    date: xpathFunctionWithString("Date"),
    dateOfBirth: xpathFunctionWithIndex(2),
    tin: xpathFunctionWithString("Tin"),
    tinText: xpathFunctionWithIndex(5),
    nationalId: xpathFunctionWithString("National"),
    nationalIdText: xpathFunctionWithIndex(6),
    biography: xpathFunctionWithString("Bio"),
    biographyText:xpathFunctionWithIndex(3),
    relatedOrg: xpathFunctionWithTwoStrings("Organizations"),
    relatedOrgText: xpathFunctionWithIndex(11),
    relatedPeople: xpathFunctionWithTwoStrings("People"),
    relatedpeopleText: xpathFunctionWithIndex(10),
    address: xpathFunctionWithString("Address"),
    addressText: xpathFunctionWithIndex(9),
    jurisdiction: xpathFunctionWithString("Aff"),
    jurisdictionText: xpathFunctionWithIndex(8),
    ardisId: 'div[class*="node even"] .title> :nth-child(2) > :nth-child(3)',
    ardisIdText: '//*[@class="text-lighter text-right"]/text()',
    pep: xpathFunctionWithString("Pep"),
    pepText: xpathFunctionWithIndex(6),
    position: xpathFunctionWithString("Position"),
    positionText: xpathFunctionWithIndex(9),
    more: '.left-side > :nth-child(1) img[alt*="doneImage"]',
    explore: ".btn-selected-result > :nth-child(3)",
    continue: "//*[@class='fab-explore btn-float btn-action']//*[contains(text(),'Continue')]",
    keyIdentifiers: ".MuiBox-root > :nth-child(2)",
    akaExplore: xpathContainsText('AKA'),
    akaExploreText: "//div[contains(text(),'AKA')]/parent::div//div[2]",
    ardisIdExplore: "(//*[contains(text(),'ARDIS ID')])[1]",
    ardisIdExploreText: "(//div[contains(text(),'ARDIS ID')]/parent::div/div[2])[1]",
    uniExplore: xpathContainsText('Unique'),
    uniExploreText: "(//div[contains(text(),'Unique')]/parent::div/div[2])[1]",
    jurisdictionExplore: "//*[contains(text(),'Jurisdiction Exposure')]",
    jurisdictionExploreText: "(//div[contains(text(),'Jurisdiction')]/parent::div/div[2])[1]",
    statusExplore: xpathContainsText('Status'),
    statusExploreText: "(//div[contains(text(),'Status')]/parent::div/div[2])[1]",
    relatedDatesExplore: "//*[contains(text(),'Related Dates')]",
    relatedDatesExploreText: "(//div[contains(text(),'Related')]/parent::div/div[2])[1]",
    positionsExplore: xpathContainsText('Positions'),
    positionsExploreText: "(//div[contains(text(),'Positions')]/parent::div/div[2])[1]",
    alertsExplore: xpathContainsText('Alerts'),
    alertsExploreText: "(//div[contains(text(),'Alerts')]/parent::div/div[2])[1]",
    politicalProfile: ".MuiBox-root > :nth-child(7)",
    businessProfile: ".MuiBox-root > :nth-child(10)",
    judicial: ".MuiBox-root > :nth-child(16)",
    relationships: ".MuiBox-root > :nth-child(12)",
    graph: "//*[@data-id='layer0-selectbox']",
    newsSearchExplore: '.MuiBox-root > :nth-child(18)',
    clickHere: '//*[@class="main-color font-16"]/div/div[1]',
    left: '#checkboxes-tags-demo_light',
    right: '#checkboxes-tags-demo_undefined',
    dropDownMenu: "li[data-option-index]",
    newsSearchCard: '//*[@class="row right-entity newsSearch-heightCalc newSearchCardContainer"]//div[@class="news-article"]',
    judicalProfileCard: '//div[@class="row component-list judicial"]//div[@class="hit-selected"]',
    businessProfileCard: '//div[@class="businessprofile_card card"]//div[@class="card-item"]',
    politicalProfileCard: '//div[@class="politicalprofile_card card"]//div[@class="card-item"]'

   
}
